# Generated by Django 6.0.2 on 2026-03-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='students',
        ),
    ]
